### ISSUE TITLE
In wxPython demo AUI_DockingWindowMgr does not work (showes TypeError)

### ISSUE THREAD

**Issue by AndreySerov** [wxWidgets/Phoenix#1024]
**Operating system**: Windows 10
**wxPython version & source**:          wxPython-demo-4.0.3
**Python version & source**:            WinPython 3.7.0.2

![image](https://user-images.githubusercontent.com/43737633/46269802-f827bf00-c575-11e8-8e7d-40a7212736d2.png)

**Comment by RobinD42** [comment]
Fixed by #1056

**Comment by coding-machine0001** [comment]
This exact same error is still present in wxDemo for wxPython 4.0.3.

Has it been fixed yet?

**Comment by RobinD42** [comment]
It has been fixed for 4.0.4
