### ISSUE TITLE
EVT_KEY_DOWN is not called for a non-English keyboard layout in Linux

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/Phoenix#1144]
**Operating system**: Ubuntu 18.10
**wxPython version & source**:          wxPython 4.0.4 self-build.
**Python version & source**:            Python 3.6 stock

**Description of the problem**: EVT_KEY_DOWN is not called for a non-English keyboard layout (Russian layout for example) in Linux for TextCtrl and StyledTextCtrl. The problem is observed in Ubuntu, everything works under Windows.

Code for test:

```python
# -*- coding: utf-8 -*-

import wx
import wx.stc


class MyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, "Key test")
        self.SetSize((600, 500))

        self.textCrl = wx.TextCtrl(self, style=wx.TE_MULTILINE)
        self.styledTextCtrl = wx.stc.StyledTextCtrl(self)
        self.logCtrl = wx.TextCtrl(self, style=wx.TE_READONLY | wx.TE_MULTILINE)

        self.textCrl.Bind(wx.EVT_KEY_DOWN, handler=self._onTextCtrlKeyDown)
        self.styledTextCtrl.Bind(wx.EVT_KEY_DOWN, handler=self._onStyledTextCtrlKeyDown)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.textCrl, 1, wx.EXPAND)
        sizer.Add(self.styledTextCtrl, 1, wx.EXPAND)
        sizer.Add(self.logCtrl, 1, wx.EXPAND)
        self.SetSizer(sizer)

    def _onTextCtrlKeyDown(self, event):
        text = '[TextCtrl] EVT_KEY_DOWN. Key code = {}\n'.format(event.GetKeyCode())
        self.logCtrl.AppendText(text)
        event.Skip()

    def _onStyledTextCtrlKeyDown(self, event):
        text = '[StyledTextCtrl] EVT_KEY_DOWN. Key code = {}\n'.format(event.GetKeyCode())
        self.logCtrl.AppendText(text)
        event.Skip()


if __name__ == '__main__':
    app = wx.App(0)

    frame = MyFrame(None)
    app.SetTopWindow(frame)
    frame.Show()

    app.MainLoop()
```

Screenshot in Ubuntu (5 characters were entered, 2 events were triggered.):

![evt_key_down](https://user-images.githubusercontent.com/166281/51274060-40f96b80-19df-11e9-9c9d-b14fc36fc002.png)

**Comment by swt2c** [comment]
I can reproduce in wxWidgets.  It has been reported before also:
https://trac.wxwidgets.org/ticket/18054

**Comment by swt2c** [comment]
Pull request opened with fix:
https://github.com/wxWidgets/wxWidgets/pull/1186

**Comment by RobinD42** [comment]
Fixed by #1150

**Comment by DarkFenX** [comment]
I have the same issue for ListCtrl (using events for ctrl-a hotkeys). @RobinD42, does the fix resolve it too, and which release will have it included?

**Comment by swt2c** [comment]
It probably should resolve it, but you may want to test one of the latest snapshot builds to be sure:
https://wxpython.org/Phoenix/snapshot-builds/

It will be in 4.0.5 (if/when that happens) and 4.1.x.

**Comment by DarkFenX** [comment]
I'm using linux so I guess I will have to wait. Not fond of building it myself.

**Comment by DarkFenX** [comment]
Issue is supposed to be fixed, but my use-case still doesn't work. How do i detect if user pressed Ctrl-A regardless of current keyboard layout?

event.GetKeyCode() returns 0 for "Ф" ("A" in russian layout).

**Comment by swt2c** [comment]
I am not sure.  You may want to ask on wxWidgets mailing list.

**Comment by DarkFenX** [comment]
Did that: https://discuss.wxpython.org/t/34180

**Comment by swt2c** [comment]
If you don't get any response there you may want to ask *wxWidgets* not wxPython.

**Comment by DarkFenX** [comment]
Oops, sorry, missed this difference :D will do
