### ISSUE TITLE
HtmlWindow demo hard crash on 'With widgets' button

### ISSUE THREAD

**Issue by Metallicow** [wxWidgets/Phoenix#688]
**Operating system**: Win7
**wxPython version**: wxPython-4.0.0rc1.dev3597+5f1ee01-cp27-cp27m-win32
**Stock or custom build**: snapshot-build
**Python version**: 2.7.14
**Stock or custom build**: stock

**Description of the problem**:
hard crash in the 'HtmlWindow' demo when pressing the 'With widgets' button.

**Comment by RobinD42** [comment]
Are you sure you're using the newest snapshot? This (or something like it) was fixed several weeks ago, and it's not happening to me in my current workspace.

**Comment by Metallicow** [comment]
I'll try and reproduce this on a fresh install...

**Comment by Metallicow** [comment]
@RobinD42 Yep it's still happening. Tested on Win7 Ultimate SP1 this time with `wxPython-4.0.0rc1.dev3607+c1a0a4d-cp27-cp27m-win32.whl` fresh Python2.7.14 install with only wxPy snapshot, Pillow, six installed.

**Comment by RobinD42** [comment]
I wasn't able to duplicate this on Win7 with Python 2.7 either. Anything else that is uncommon about your test system?

**Comment by Metallicow** [comment]
I don't believe so. I'll see if I can look/toy around with the demo code by commenting lines out and see if there is a problem there.

**Comment by Metallicow** [comment]
@RobinD42 
I've found the culprit.

in `data/widgetTest.htm` I commented out this and it stopped hard crashing. Any Ideas?
```
Recognize this one?<br>
<wxp module="ScrolledWindow" class="MyCanvas" height=300 width=100%>
</wxp>
```

**Comment by RobinD42** [comment]
Perhaps it's not able to import the module for some reason?

**Comment by Metallicow** [comment]
@RobinD42 
Ok the newest snapshot demo with ...
pypi wxPython-4.0.0b2-cp27-cp27m-win32.whl
Tested from inside the demo. Hard crashed on button click
Tested HtmlWindow.py itself. No crash on button click

Ok the newest snapshot demo with the newest snapshot build.
Same thing.

It appears The wxDemo Loader or something is screwing up again. So whatta think? Is this a valid issue or should it be marked a issue to look for again whenever ya get time to review the new framework code I whipped up?
